#!/usr/bin/python3.11

import sys

import error_handling
from scanner import Scanner
from parser import Parser
# from ast_printer import ASTPrinter
from interpreter import Interpreter


def run(interpreter: Interpreter, src: str):
    scanner = Scanner(src)
    tokens = scanner.scan_tokens()
    parser = Parser(tokens)
    statements = parser.parse()

    if error_handling.HAS_ERROR:
        return

    # print(ASTPrinter().print(expr))
    interpreter.interpret(statements)


def run_file(interpreter, fname):
    run(interpreter, open(fname).read())
    if error_handling.HAS_ERROR:
        sys.exit(65)
    if error_handling.HAS_RUNTIME_ERROR:
        sys.exit(70)


def run_prompt(interpreter):
    while True:
        try:
            line = input(">>> ")
        except EOFError:
            # CTRL-D exit the interpreter
            break

        if line:
            run(interpreter, line)
            error_handling.HAS_ERROR = False


def main(args):
    interpreter = Interpreter()
    if len(args) > 2:
        print("Usage: ./lox [script]")
        sys.exit(65)
    elif len(args) == 2:
        run_file(interpreter, args[1])
    else:
        run_prompt(interpreter)


if __name__ == "__main__":
    main(sys.argv)
