#!/usr/bin/python3.11

import sys

from pylox import PyLox


def main(args):
    if len(args) > 2:
        print("Usage: ./lox [script]")
        sys.exit(65)
    elif len(args) == 2:
        PyLox().run_file(args[1])
    else:
        PyLox().run_prompt()


if __name__ == "__main__":
    main(sys.argv)
